# Generated by Django 5.1.5 on 2025-01-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedBookings',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pass_id', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(upload_to='uploads/vehicles/')),
                ('password', models.CharField(max_length=50)),
                ('live_location', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(upload_to='uploads/vehicles/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_id', models.IntegerField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('OTP', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='driver.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.drivers')),
                ('pass_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger')),
            ],
        ),
    ]
