# Generated by Django 5.1.5 on 2025-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(upload_to='uploads/vehicles/')),
                ('password', models.CharField(max_length=50)),
                ('live_location', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(upload_to='uploads/vehicles/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
