# Generated by Django 5.1.5 on 2025-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdrivers',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
