# Generated by Django 5.1.5 on 2025-01-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivers',
            old_name='live_location',
            new_name='current_location',
        ),
    ]
